backend:
  name: github
  repo: Budo84/proflama
  branch: main

media_folder: "docs/public/img"
public_folder: "/img"

collections:
  - name: "blog"
    label: "Articoli Blog"
    folder: "docs/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Corpo", name: "body", widget: "markdown"}
