backend:
  name: git-gateway
  branch: main

media_folder: "docs/public/img"
public_folder: "/img"

collections:
  - name: "blog"
    label: "Articoli Blog"
    folder: "docs/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Corpo", name: "body", widget: "markdown"}
  
  - name: "pages"
    label: "Pagine Sito"
    files:
      - file: "docs/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Contenuto", name: "body", widget: "markdown"}
